apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deals
  labels:
    name: deals
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: deals
    spec:
      containers:
      - name: deals
        image: yow-workshop/deal:v3
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
