apiVersion: v1
kind: Service
metadata:
  name: deals
  labels:
    name: deals
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8081
    targetPort: 8080
  selector:
    name: deals
   type: NodePort
